//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_PCL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eKino_PCL.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nije u ispravnom formatu..
        /// </summary>
        public static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezan..
        /// </summary>
        public static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno..
        /// </summary>
        public static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno..
        /// </summary>
        public static string lname_req {
            get {
                return ResourceManager.GetString("lname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste neispravnu lozinku..
        /// </summary>
        public static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite pristupne podatke..
        /// </summary>
        public static string login_req {
            get {
                return ResourceManager.GetString("login_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravni pristupni podaci ili je vaš nalog neaktivan..
        /// </summary>
        public static string login_user_err {
            get {
                return ResourceManager.GetString("login_user_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime nije pronađeno ili je vaš nalog neaktivan..
        /// </summary>
        public static string login_usr_err {
            get {
                return ResourceManager.GetString("login_usr_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stara lozinka nije ispravna..
        /// </summary>
        public static string password_err {
            get {
                return ResourceManager.GetString("password_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka treba da sadrži najmanje 3 karaktera..
        /// </summary>
        public static string password_len {
            get {
                return ResourceManager.GetString("password_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna..
        /// </summary>
        public static string password_req {
            get {
                return ResourceManager.GetString("password_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste ocijenili film..
        /// </summary>
        public static string rating_succ {
            get {
                return ResourceManager.GetString("rating_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste se registrovali..
        /// </summary>
        public static string registration_succ {
            get {
                return ResourceManager.GetString("registration_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite sjedište..
        /// </summary>
        public static string rezervacija_err {
            get {
                return ResourceManager.GetString("rezervacija_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste rezervirali..
        /// </summary>
        public static string rezervacija_succ {
            get {
                return ResourceManager.GetString("rezervacija_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjeh.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film nema trailer..
        /// </summary>
        public static string trailer_err {
            get {
                return ResourceManager.GetString("trailer_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom izmjene podatka vašeg profila..
        /// </summary>
        public static string user_update_err {
            get {
                return ResourceManager.GetString("user_update_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke vašeg profila..
        /// </summary>
        public static string user_update_succ {
            get {
                return ResourceManager.GetString("user_update_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime treba da sadrži najmanje 3 karaktera..
        /// </summary>
        public static string username_err {
            get {
                return ResourceManager.GetString("username_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno..
        /// </summary>
        public static string username_req {
            get {
                return ResourceManager.GetString("username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite omiljeni žanr..
        /// </summary>
        public static string zanr_req {
            get {
                return ResourceManager.GetString("zanr_req", resourceCulture);
            }
        }
    }
}
