//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eKino_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o žanru..
        /// </summary>
        internal static string add_genre_succ {
            get {
                return ResourceManager.GetString("add_genre_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o filmu..
        /// </summary>
        internal static string add_movie_succ {
            get {
                return ResourceManager.GetString("add_movie_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o projekciji..
        /// </summary>
        internal static string add_projection_succ {
            get {
                return ResourceManager.GetString("add_projection_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o korisniku..
        /// </summary>
        internal static string add_usr_succ {
            get {
                return ResourceManager.GetString("add_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite izbrisati dvoranu?.
        /// </summary>
        internal static string del_dvorane_prompt {
            get {
                return ResourceManager.GetString("del_dvorane_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali dvoranu..
        /// </summary>
        internal static string del_dvorane_succ {
            get {
                return ResourceManager.GetString("del_dvorane_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite izbrisati žanr?.
        /// </summary>
        internal static string del_genre_prompt {
            get {
                return ResourceManager.GetString("del_genre_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali podatke o žarnu..
        /// </summary>
        internal static string del_genre_succ {
            get {
                return ResourceManager.GetString("del_genre_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite obrisati film?.
        /// </summary>
        internal static string del_movie_prompt {
            get {
                return ResourceManager.GetString("del_movie_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali podatke o filmu..
        /// </summary>
        internal static string del_movie_succ {
            get {
                return ResourceManager.GetString("del_movie_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite obrisati projekciju?.
        /// </summary>
        internal static string del_projection_prompt {
            get {
                return ResourceManager.GetString("del_projection_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali podatke o projekciji..
        /// </summary>
        internal static string del_projection_succ {
            get {
                return ResourceManager.GetString("del_projection_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite izbrisati uslugu?.
        /// </summary>
        internal static string del_usluge_prompt {
            get {
                return ResourceManager.GetString("del_usluge_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite obrisati korisnika?.
        /// </summary>
        internal static string del_usr_prompt {
            get {
                return ResourceManager.GetString("del_usr_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali podatke o korisniku..
        /// </summary>
        internal static string del_usr_succ {
            get {
                return ResourceManager.GetString("del_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali dvoranu..
        /// </summary>
        internal static string dvorane_add_succ {
            get {
                return ResourceManager.GetString("dvorane_add_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalni kapacitet dvorane je 20.
        /// </summary>
        internal static string dvorane_capacity {
            get {
                return ResourceManager.GetString("dvorane_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv dvorane već postoji..
        /// </summary>
        internal static string dvorane_name_err {
            get {
                return ResourceManager.GetString("dvorane_name_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime dvorane treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string dvorane_name_length {
            get {
                return ResourceManager.GetString("dvorane_name_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv dvorane je obavezan..
        /// </summary>
        internal static string dvorane_name_req {
            get {
                return ResourceManager.GetString("dvorane_name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmjenili podatke o dvorani..
        /// </summary>
        internal static string dvorane_update_succ {
            get {
                return ResourceManager.GetString("dvorane_update_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o žanru..
        /// </summary>
        internal static string edit_genre_succ {
            get {
                return ResourceManager.GetString("edit_genre_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o filmu..
        /// </summary>
        internal static string edit_movie_succ {
            get {
                return ResourceManager.GetString("edit_movie_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o projekciji..
        /// </summary>
        internal static string edit_projection_succ {
            get {
                return ResourceManager.GetString("edit_projection_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o korisniku..
        /// </summary>
        internal static string edit_usr_succ {
            get {
                return ResourceManager.GetString("edit_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa je zauzeta..
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nije u ispravnom formatu..
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezan..
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno..
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv žanra treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string genre_name_err {
            get {
                return ResourceManager.GetString("genre_name_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv žanra je obavezan..
        /// </summary>
        internal static string genre_name_req {
            get {
                return ResourceManager.GetString("genre_name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite najmanje jedan žanr!.
        /// </summary>
        internal static string genre_req {
            get {
                return ResourceManager.GetString("genre_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno..
        /// </summary>
        internal static string lname_req {
            get {
                return ResourceManager.GetString("lname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste neispravnu lozinku..
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime nije pronađeno ili je vaš nalog neaktivan..
        /// </summary>
        internal static string login_user_err {
            get {
                return ResourceManager.GetString("login_user_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis filma je obavezan..
        /// </summary>
        internal static string movie_desc_req {
            get {
                return ResourceManager.GetString("movie_desc_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje filma je obavezno..
        /// </summary>
        internal static string movie_duration_req {
            get {
                return ResourceManager.GetString("movie_duration_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv filma je obavezan..
        /// </summary>
        internal static string movie_name_req {
            get {
                return ResourceManager.GetString("movie_name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvorni naziv filma je obavezan..
        /// </summary>
        internal static string movie_org_req {
            get {
                return ResourceManager.GetString("movie_org_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer url nije u ispravnom formatu..
        /// </summary>
        internal static string movie_trailer_err {
            get {
                return ResourceManager.GetString("movie_trailer_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer filma je obavezan..
        /// </summary>
        internal static string movie_trailer_req {
            get {
                return ResourceManager.GetString("movie_trailer_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina izdavanja filma je obavezana..
        /// </summary>
        internal static string movie_year_req {
            get {
                return ResourceManager.GetString("movie_year_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda.
        /// </summary>
        internal static string msg_conf {
            get {
                return ResourceManager.GetString("msg_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poruka o uspjehu.
        /// </summary>
        internal static string msg_succ {
            get {
                return ResourceManager.GetString("msg_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string msg_war {
            get {
                return ResourceManager.GetString("msg_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string password_err {
            get {
                return ResourceManager.GetString("password_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna..
        /// </summary>
        internal static string password_req {
            get {
                return ResourceManager.GetString("password_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete sliku dimenzija većih od.
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno nema aktivnih rezervacija..
        /// </summary>
        internal static string rezervacije_process_fail {
            get {
                return ResourceManager.GetString("rezervacije_process_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste procesirali rezervacije..
        /// </summary>
        internal static string rezervacije_process_succ {
            get {
                return ResourceManager.GetString("rezervacije_process_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite najmanje jednu ulogu!.
        /// </summary>
        internal static string roles_req {
            get {
                return ResourceManager.GetString("roles_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morati odabrati red..
        /// </summary>
        internal static string row_err {
            get {
                return ResourceManager.GetString("row_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite sliku..
        /// </summary>
        internal static string slika_req {
            get {
                return ResourceManager.GetString("slika_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite vrstu!.
        /// </summary>
        internal static string type_req {
            get {
                return ResourceManager.GetString("type_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto..
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string username_err {
            get {
                return ResourceManager.GetString("username_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno..
        /// </summary>
        internal static string username_req {
            get {
                return ResourceManager.GetString("username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena usluge je obavezna..
        /// </summary>
        internal static string usluge_cijena_err {
            get {
                return ResourceManager.GetString("usluge_cijena_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali uslugu..
        /// </summary>
        internal static string usluge_del {
            get {
                return ResourceManager.GetString("usluge_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime usluge je obavezno..
        /// </summary>
        internal static string usluge_naziv_err {
            get {
                return ResourceManager.GetString("usluge_naziv_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali uslugu..
        /// </summary>
        internal static string usluge_succ {
            get {
                return ResourceManager.GetString("usluge_succ", resourceCulture);
            }
        }
    }
}
