//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmovi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmovi()
        {
            this.FilmoviZanrovi = new HashSet<FilmoviZanrovi>();
            this.Ocjene = new HashSet<Ocjene>();
            this.Projekcije = new HashSet<Projekcije>();
        }
    
        public int FilmID { get; set; }
        public string Naziv { get; set; }
        public string IzvorniNaziv { get; set; }
        public short GodinaIzdavanja { get; set; }
        public short Trajanje { get; set; }
        public string Opis { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
        public string Trailer { get; set; }
        public bool Aktivan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmoviZanrovi> FilmoviZanrovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekcije> Projekcije { get; set; }
    }
}
