//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjene
    {
        public int OcjenaID { get; set; }
        public int FilmID { get; set; }
        public int ClanID { get; set; }
        public System.DateTime Datum { get; set; }
        public int Ocjena { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
        public virtual Filmovi Filmovi { get; set; }
    }
}
