//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekcije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekcije()
        {
            this.Ulaznice = new HashSet<Ulaznice>();
        }
    
        public int ProjekcijaID { get; set; }
        public int FilmID { get; set; }
        public int DvoranaID { get; set; }
        public int UslugaID { get; set; }
        public System.DateTime DatumProjekcije { get; set; }
        public bool Aktivna { get; set; }
    
        public virtual Dvorane Dvorane { get; set; }
        public virtual Filmovi Filmovi { get; set; }
        public virtual Usluge Usluge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ulaznice> Ulaznice { get; set; }
    }
}
