//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacije()
        {
            this.Ulaznice = new HashSet<Ulaznice>();
        }
    
        public int RezervacijaID { get; set; }
        public System.DateTime VrijemeRezervacije { get; set; }
        public string Napomena { get; set; }
        public int ClanID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
        public virtual Korisnici Korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ulaznice> Ulaznice { get; set; }
    }
}
