//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sjedala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sjedala()
        {
            this.Ulaznice = new HashSet<Ulaznice>();
        }
    
        public int SjedaloID { get; set; }
        public int DvoranaID { get; set; }
        public short PozicijaX { get; set; }
        public short PozicijaY { get; set; }
        public bool isZauzeto { get; set; }
    
        public virtual Dvorane Dvorane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ulaznice> Ulaznice { get; set; }
    }
}
