//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ulaznice
    {
        public int UlaznicaID { get; set; }
        public int ProjekcijaID { get; set; }
        public int SjedaloID { get; set; }
        public int RezervacijaID { get; set; }
        public bool Procesirano { get; set; }
    
        public virtual Projekcije Projekcije { get; set; }
        public virtual Rezervacije Rezervacije { get; set; }
        public virtual Sjedala Sjedala { get; set; }
    }
}
